### PR TITLE
Add support for Rails 6.1 and Ruby 3.0

### PR DESCRIPTION
**Pull request by francois-ferrandis**
Hi there!

I updated the gemspec, updated the gems to reasonably recent versions and set the ruby version to 3.0.1.

I ran the test manually and they passed for Rails 5.2, Rails 6.0 and Rails 6.1. Ruby 2.6 / 3.0 also pass.

| ruby version | rails version | tests  |
|--------------|---------------|--------|
| 2.6.6        | 5.2.6         | PASSED |
| 2.6.6        | 6.0.3.7       | PASSED |
| 2.6.6        | 6.1.3.2       | PASSED |
| 3.0.1        | 5.2.6         | PASSED |
| 3.0.1        | 6.0.3.7       | PASSED |
| 3.0.1        | 6.1.3.2       | PASSED |

Note: I am not experienced with gem development, so tell me if committing `.ruby-version` is a bad idea or something.

Thank you very much! :handshake:

### CODE REVIEW

**Comment by francois-ferrandis** [comment]
¡muchas gracias!

Could you publish a new version at https://rubygems.org/gems/iban_bic ? :upside_down_face:

**Comment by francois-ferrandis** [comment]
@joseluispodemos Any chance you could publish a new version at https://rubygems.org/gems/iban_bic ? :pray:

**Comment by joseluispodemos** [comment]
Thanks @francois-ferrandis.

The new versión 1.4.5 is already published at rubygems: https://my.diffend.io/gems/iban_bic/1.4.4/1.4.5

Something missing?

**Comment by francois-ferrandis** [comment]
Woops @joseluispodemos I did not see that. :grimacing: 

Thank you. :pray:

**Comment by joseluispodemos** [comment]
Sorry for not replying to your previous message. Thank you! 🙏🏻

**Pull request merged**
